### ISSUE TITLE
Update SSP support to 1.0

### ISSUE THREAD

**Issue by markaren** [CATIA-Systems/FMPy#104]
It would be nice if the SSP support was updated from `Draft20171219` to `1.0`.

**Comment by t-sommer** [comment]
Without publicly available test models it's very difficult to update the implementation. The [SSP website](https://ssp-standard.org/) currently lists no tools with SSP support and no demo models.

**Comment by markaren** [comment]
> no demo models

This is indeed a pain point for adoption.

**Comment by t-sommer** [comment]
Please re-open when an updated example is available.

**Comment by chrbertsch** [comment]
@JochenKoehler @pmai @Hans-Martin-Heinkel: It is really important to have publicly available SSP 1.0 examples, so that tools like fmpy could release and test SSP-support.

**Comment by JochenKoehler** [comment]
Hi Christian,

from my point of view, it would very useful to provide the examples to anybody who is interested to support the standard. Hence it should be public.
If this is a big issue we should think about taking the Modelica models, import it to a open-source tool (e.g. Open-Modelica …) and export the model from this tool.

Could this be a workaround / alternative?

Best regards
Jochen

Von: Christian Bertsch <notifications@github.com>
Gesendet: Montag, 27. Januar 2020 21:28
An: CATIA-Systems/FMPy <FMPy@noreply.github.com>
Cc: Koehler Jochen FRD DIRV2 <jochen.koehler@zf.com>; Mention <mention@noreply.github.com>
Betreff: Re: [CATIA-Systems/FMPy] Update SSP support to 1.0 (#104)


@JochenKoehler<https://github.com/JochenKoehler> @pmai<https://github.com/pmai> @Hans-Martin-Heinkel<https://github.com/Hans-Martin-Heinkel>: It is really important to have publicly available SSP 1.0 examples, so that tools like fmpy could release and test SSP-support.
