### ISSUE TITLE
Is it possible to save the model after initialization?

### ISSUE THREAD

**Issue by julienlmet** [CATIA-Systems/FMPy#178]
I'm currently working with a model whose simulation lasts about 240seconds. It could be great if this simulation was quicker since I've to run it hundreds of times. The only difference between the simulations I have to run are the inputs that I inject.

The specificity here is that I'm not running all my simulations at the same time because I get the inputs that I want to inject in my model at a frequency that I do not control: when a set of inputs is ready, I launch a simulation. If I had wanted to run all the simulations at the same time, I would have follow https://github.com/CATIA-Systems/FMPy/issues/30#issuecomment-372374408.

When I put loggers into function `simulate_fmu`, I get following information:
- First steps (loading model description, fmu instantiation & applying start values) are quick (about 0.5sec)
- Calling `initialize` takes a lot of time (about 140sec)
- The time in the simulation loop is, for my model close the initialization time (about 100sec for simulation loop)

# What I'd like (if it is possible)
- Load model description, perform fmu instantiation
- Call `initialize`
- "Save" somehow the fmu in this state in order to be able to reload it
- When loading the fmu in this state (if it is possible), I'd have to inject inputs after having called `initialize` and then run the simulation loop.

# What I've already tried
- I've tried to save the model after the `initialize` call with `joblib` and `pickle` but it does not work (`Can't pickle <class 'ctypes.CDLL.__init__.<locals>._FuncPtr'>: it's not found as ctypes.CDLL.__init__.<locals>._FuncPtr`)

# Questions
- Is there a way with current version of FMPy to achieve what I'd like?

**Comment by t-sommer** [comment]
You can serialize / deserialize the FMU state if the FMU supports it ( `canGetAndSetFMUstate="true"`). Take a look at  https://github.com/CATIA-Systems/FMPy/blob/master/tests/test_serialize_fmu_state.py for an example.

**Comment by gaspard-met** [comment]
Hello @t-sommer ,

I know the issue is been closed for a while now, but to me a part of the issue is still unanswered: it is possible to serialize the actual FMU model (not the state) with pickle/cloudpickle/dill/joblib ? 
They seem to throw of an error because they can't serialize ctypes properly (see https://github.com/uqfoundation/dill/issues/342)

Do you know of any workarounds ? 

thanks !

**Comment by t-sommer** [comment]
The FMU instance itself cannot be serialized because it depends on the extracted FMU and loaded shared library. However you could create a wrapper that implements `__setstate__` and `__getstate__` to serialize and deserialize the dependencies.

Can you elaborate on why it would be necessary to pickle the whole object vs. just the FMU state?

**Comment by gaspard-met** [comment]
P.S.: stumbled on this project after writing my message, and it's the closest thing I've seen to what we would like to do
https://github.com/mbonvini/LambdaSim

**Comment by t-sommer** [comment]
Can't you just read the `*.fmu` into a byte array (that can be serialized) and restore it when you need it?
