### ISSUE TITLE
Stepwise simulation of model exchange

### ISSUE THREAD

**Issue by Maaeve** [CATIA-Systems/FMPy#222]
I would like to simulate my Model exchange FMU in real-time in Python.
I checked the possibilities of both Co-Simulation and Model Exchange.
In Co-Simulation, I saw that there is the possibility to work with DoStep, but due to Solver export reasons, I need to switch to Model Exchange.
My questions is if there is also a similar function for the Model Exchange FMU within FMPy?

Thanks for your response.

**Comment by t-sommer** [comment]
> due to Solver export reasons, I need to switch to Model Exchange

What is holding you back?

**Comment by Maaeve** [comment]
Thanks for your quick response.
I can only export my model with the Cvode solver in Co-Simulation fromout Dymola. The problem is that Cvode doesn't keep a fixed step_size in between.
So if I would use discrete steps of 10s as required in the lab starting from 0, the model should only be calculated at 0s, 10s, 20s, 30s, ...
But if some events occur at e.g. 5s, my Cvode solver solves more like 0s, 5s, 10s, 20s, 30s, ...
I assume that the Euler solver only calculates the model at 0s, 10s, 20s, 30s, ...
But I don't think I can change the solver of my Co-Simulation within FMPy to Euler or is this a misunderstanding from my side?
So that is the reason why I think I should switch to Model-Exchange.
I should mention that this is my first time using the FMU, so I'm not familiar with all the possible commands.

**Comment by t-sommer** [comment]
In Dymola you can select the solver for your Co-Simulation FMU under `Simulation Setup > General > Integration > Algorithm`. This dialog also allows you to set the `Fixed Integrator Step`.

**Comment by Maaeve** [comment]
The problem is that I already went into this set-up. So I first changed the Real-time tab to inline integration with the implicit Euler at 10s optimised step size.
Afterwards I changed the general tab to Euler at fixed time steps of 10s.
If I then go to Translate>FMU, then I can only use the Co-Simulation using Cvode as I don't have the 'Binary Export license' to export my Dymola Solver.
So I suppose that Dymola internally switches the Euler solver to Cvode solver when exporting the FMU?
So when I run my simulations in pure Dymola and again in FMPy, I get different results.
Temperatures are e.g. 0.5°C different.
When I import my FMPy simulation results in Dymola and look into e.g. a boolean value of my thermostat, I see that:
-the pure Dymola Implicit Euler only changes its state at the requested time steps
-the result from FMPy changes its states at other times as well, such as second 13 instead of second 20.
To that's why I think that it internally switches to the Cvode and not to the Euler.

**Comment by KarlWernersson** [comment]
Hi Is there a specific reason why you want to use Model Exchange?
If you export inline solver with model exchange from Dymola you need to make sure that the solver you use is called with the fix step size used when exporting the FMU with the inline solver. And since you are using inline integration you have already embedded the solver in the FMU. Because of this we usually recommend to use co-simulation when exporting an inline FMU from Dymola.
If you have a specific reason to use Model Exchange for you inline FMU, make sure that the solver used to integrate your FMU is fix step and uses the desired fix step size. You can find the reqired step size in the modelDescription.xml file in the FMU

**Comment by Maaeve** [comment]
Hi, Thanks for your feedback.
I thought to switch to Model Exchange due to the unavailability of exporting my Euler solver from Dymola.
But apparantly, the Dymola distributor told me today that this is possible, so in that way I will try to proceed with Co-simulation based on your recommandations. 
I tried to import my generated Dymola FMU again into Dymola and run the simulation there.
Although the generation of the FMU doesn't provide any errors, the simulation fails, while the original model doesn't.
So I would like to use this opportunity to ask if you maybe have similar experience with FMU export/import?
In both import/export of the FMU, I set the inline integration with Implicit Euler, the Euler solver with everywhere the same step-size.

**Comment by KarlWernersson** [comment]
Hi

By activating inline integration and export them model with cvode, cvode will be disalbed and the solver used for inline integration will be used instead. You should always test your FMU in your exporting tool and verify that it simulates correctly before movign it to other platforms. Since Dymola is a very advanced tool that do, a lot of symbolic manipulation of the model a common mistake is to make a sub system, make an fmu out of it, and not test it properly.  When you cut out a sub model, you lose the connections of the greater system the FMU in this case loses the possibility to utilize the equations of the other parts of the greater model and will no longer simulate, as the equations in the fmu are not setup properly. 

Good practice is to first, verify that the Modelica model that will become an FMU can simulate by itself unconnected, and that it can simulate with fixed inputs. If this works, export the model to an FMU reimport it to Dymola and try to simulate this FMU unconnected and with the same set of fixed inputs. If the Modelica model works but the FMU fails, there is probably some error with the export or a very unstable model. In any case. If that happens I would recommend you to open a ticket with Dymola support and supply your Modelica model, your FMU and your modelica test model. Then it is easy for support to figure out what goes wrong and possibly fix it if it is an error withe the FMU export of Dymola

**Comment by Maaeve** [comment]
Thank you for your explanation.
I've done the following simulations:
1. run with the Dassl solver and no inline integration in pure Dymola
2. run with Euler solver and inline integration with the implicit Euler in pure Dymola
3. exported my model with the settings of 2 as an FMU, imported it back into Dymola and simulated with the settings as I exported so I again set the inline integration to implicit Euler together with the Euler solver at 10s

The results of 1 and 2 are the same, but this is not the case for 3.
So it seems that the export to an FMU fails in some way.

**Comment by KarlWernersson** [comment]
Hi, yes most likely. You should report it to Dymola support together with your model and they can look at it there.

**Comment by Maaeve** [comment]
Thanks for your help and feedback.
