### ISSUE TITLE
fmi2DoStep: fmi2DoStep is called without initialization sequence before

### ISSUE THREAD

**Issue by Krzysztofolech** [CATIA-Systems/FMPy#315]
Hi 
I am creating a automatic python engine for multithreaded fmu simulation.
It is working Fine for most simulations but on at list one:
https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/SimulationX/3.7.41138/DoublePendulum
It is having really strange error
I initialize it just before I do step and  then start a loop and apply inputs (in that case there are no inputs) so I basilic initialize a fmu then try to do step and I have a error that is saying that I haven't initialize it.
I do not know what I am doing wrong.
I try different fmu washout applying imputes and it works fine

**Comment by chrbertsch** [comment]
This seems to be a problem of the FMU.
In the FMI Cross Check no tool has reported successful simulation of this FMU, see https://github.com/modelica/fmi-cross-check/tree/master/results/2.0/cs/win64/SimulationX/3.7.41138 
Anaway, this FMU was created with a very old version of Simulation, there is a new version available at: https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/SimulationX/4.0.4/DoublePendulum. What happens if you try with this FMU?
This can at least be simulated by SimulationX :-)
https://github.com/modelica/fmi-cross-check/tree/master/results/2.0/cs/win64/SimulationX/4.0.4/SimulationX/4.0.4/DoublePendulum

**Comment by Krzysztofolech** [comment]
Unfortunately newer one also do not work on my engine. 
I will try other simulation to check if any other Fmu case the same error

**Comment by Krzysztofolech** [comment]
Ok I figured it out  the issue previously I mostly use FMU 1.0 as a test object now I started testing FMU 2.0 and some of them works fine with only:
Fmu.instantiate()
But not all of them them FMU 2.0 should have all:
Fmu.instantiate()
Fmu.enterInitializationMode()
Fmu.exitInitializationMode()
